### ISSUE TITLE
Why using linear least square when doing transformation estimation ?What's the advantage? Do you publish any paper?

### ISSUE THREAD

**Issue by Yukina1996** [YuePanEdward/LLS-LOAM#1]

**Comment by YuePanEdward** [comment]
In my opinion, LLS do not have the iterative procedure involved in non-linear optimization(NLO) methods such as GN and LM so LLS should be a bit faster. Besides, when the rotation angle is relatively small, LLS's result would be close to NLO's. 
We haven't published any paper yet. 
A reference is: François Pomerleau, Francis Colas and Roland Siegwart (2015), "A Review of Point Cloud Registration Algorithms for Mobile Robotics".
Thanks.
