### ISSUE TITLE
Apollo-SouthBay Dataset

### ISSUE THREAD

**Issue by streamB** [YuePanEdward/LLS-LOAM#2]
Hi, thanks for this great work. 

I want to use the **Apollo-SouthBay Dataset** to do some testing work, but the link you provided seemed to be outdated, and I can't find it on the Internet after a lot of searches.

Could you please provide an alternative download link to the dataset? Thanks a lot.

**Comment by YuePanEdward** [comment]
Sorry for a late reply. In my opinion, the Apollo-SouthBay Dataset has been removed from the website last year. However, there's an alternative dataset available at [Apollo Scape](http://apolloscape.auto/self_localization.html#to_dataset_href).
