### ISSUE TITLE
May I ask why the reuslts are not very promising? 

### ISSUE THREAD

**Issue by shibowing** [YuePanEdward/LLS-LOAM#3]
Hi, Thank you for sharing your work.

I have tested your code on KITTI dataset with your default parameters. However, the results are not very promising, which is much worse than yours. May I ask do you know the potential reasons? 
Thank you very much. 

![kitti_lls_loam4](https://user-images.githubusercontent.com/29483569/80840356-21358900-8bcb-11ea-91a0-226e3c82c765.png)

**Comment by YuePanEdward** [comment]
Hi, I am sorry that this version is not quite stable and the performance is not good. However, by tuning the parameters, you can reproduce the results listed in the table. Besides, I am currently work on a new version of lls-loam (with ATE 0.66, ARE 0.003, 10Hz on KITTI seq 00) and I will publish it soon. 
Thanks a lot for your interest.

**Comment by shibowing** [comment]
That is a great result! Would you mind providing good parameters for me?
For the new version lls-loam, Do you only use laser measurements? or you
fuse other sensors? Do you have any published papers?

Thank you very much!

Shibo Zhao

**Comment by YuePanEdward** [comment]
Sorry for the late reply. Please refer to [MULLS](https://github.com/YuePanEdward/MULLS).
