### ISSUE TITLE
Z drift problem, do you have any better ideas?

### ISSUE THREAD

**Issue by hunkyu** [YuePanEdward/LLS-LOAM#5]
Z drift problem, do you have any better ideas?

**Comment by YuePanEdward** [comment]
Sorry for the late reply.
Please refer to [MULLS](https://github.com/YuePanEdward/MULLS). 
In my opinion, there are two solutions to ease the z drift.
1. intrinsic angle calibration, please refer to this issue [[CAE-LO  #4]](https://github.com/SRainGit/CAE-LO/issues/4).
2. balanced sampling on the point correspondence contributing to the constraints on each axis (X,Y, Z).

**Comment by hunkyu** [comment]
My experience is that the landing line will cause the pitch direction to be unstable, resulting in inaccurate estimation of the z direction, especially for the 16-line lidar.Does MULLS perform better in vlp16？
